In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

py torch

# py-torch

In [55]:
import torch
a=torch.tensor(3)
print(a)

tensor(3)


In [56]:
import torch
a=torch.tensor(3)
print(a)
print(type(a))

tensor(3)
<class 'torch.Tensor'>


In [10]:
a=torch.tensor([2,3,4,5])
print(a.shape)

torch.Size([4])


In [3]:
import torch
a=torch.tensor([2,3,4,5])
print(a.size())

torch.Size([4])


In [12]:
a=torch.tensor([[2,3],[4,5]])
a.numel()

4

In [3]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [18]:
torch.full((3,3),446)

tensor([[446, 446, 446],
        [446, 446, 446],
        [446, 446, 446]])

In [20]:
torch.arange(2,35,8)

tensor([ 2, 10, 18, 26, 34])

In [28]:
torch.rand(2,3)

tensor([[0.7073, 0.8248, 0.6335],
        [0.3226, 0.9460, 0.3169]])

In [29]:
torch.randn(2,3)

tensor([[ 1.3013,  1.3786, -1.0356],
        [ 0.0426, -1.4069,  0.7881]])

In [5]:
import torch
a=torch.tensor([2,3,4,5])
print(a.ndim)

1


In [6]:
import torch
a=torch.tensor([2,3,4,5])
print(a.device)

cpu


In [10]:
a=torch.full((2,3),1)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [13]:
torch.zeros(2,3,dtype=int)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones(2,3,dtype=int)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[[1,2]])

tensor([[5, 5, 6],
        [6, 7, 8]])


In [16]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[[1,2],1])

tensor([5, 7])


In [21]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[[0,1,2],2])

tensor([4, 6, 8])


In [22]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[0:3,0:1])

tensor([[2],
        [5],
        [6]])


In [26]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[:3,0])

tensor([2, 5, 6])


In [27]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[2:3])

tensor([[6, 7, 8]])


In [54]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a[-1:,-1:])

tensor([], size=(1, 0), dtype=torch.int64)


In [31]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(a.sum())

tensor(46)


In [32]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(sum(a))

tensor([13, 15, 18])


In [34]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
b=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(torch.subtract(a,b))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
b=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(torch.multiply(a,b))

In [35]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
b=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(torch.divide(a,b))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [38]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
b=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(torch.argmax(a))

tensor(8)


In [40]:
a=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
b=torch.tensor([[2,3,4],[5,5,6],[6,7,8]])
print(torch.argmax(b))

tensor(8)


In [44]:
a=torch.tensor([44,22,66,77,33])
print(a>40)

tensor([ True, False,  True,  True, False])


In [45]:
a=torch.tensor([44,22,66,77,33])
print(a[a>40])

tensor([44, 66, 77])


In [48]:
a=torch.tensor([44,22,66,77,33])
print(a[a<35])

tensor([22, 33])
